# Generated by Django 5.1.4 on 2024-12-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bookmark_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_photo',
        ),
    ]
